import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/utils';

const inter = Inter({ subsets: ['latin'] });

const styles = {
  container: `flex flex-col min-h-[calc(100dvh)]`,
  childrenContainer: `mt-[70px] relative flex-grow`,
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'dark')}>
        <div className={styles.container}>
          <main className={styles.childrenContainer}>{children}</main>
        </div>
      </body>
    </html>
  );
}
