// Add types
export const tracks = [
  {
    imageUrl: 'https://i.imgur.com/MHwee14.jpg',
    title: 'Bad Blood',
    artist: 'Taylor Swift',
    album: 'Deluxe',
    duration: '3:31',
    yearPublished: '1989',
    valuation: 75,
    originality: 8,
  },
  {
    imageUrl: 'https://i.imgur.com/MHwee14.jpg',
    title: 'Love Me Enough (feat. Monica & Keyshia Cole)',
    artist: 'Nicki Minaj, Monica, Keyshia Cole',
    album: 'Pink Friday 2 (Gag City Deluxe)',
    duration: '3:51',
    yearPublished: '2023',
    valuation: 80,
    originality: 7,
  },
  {
    imageUrl: 'https://i.imgur.com/Gpvu8O3.jpg',
    title: 'Grown Woman',
    artist: 'Beyonce',
    album: 'Grown Woman',
    duration: '5:10',
    yearPublished: '2013',
    valuation: 80,
    originality: 7,
  },
  {
    imageUrl: 'https://i.imgur.com/RvDsQIX.jpg',
    title: 'Rise Up',
    artist: 'Sum 41',
    album: 'Rise Up',
    duration: '3:16',
    yearPublished: '2023',
    valuation: 70,
    originality: 6,
  },
  {
    imageUrl: 'https://i.imgur.com/uh1Vexs.jpg',
    title: 'Not My Fault (with Megan Thee Stallion)',
    artist: 'Renee Rapp, Megan Thee Stallion',
    album: 'Not My Fault (with Megan Thee Stallion)',
    duration: '2:50',
    yearPublished: '2023',
    valuation: 90,
    originality: 9,
  },
  {
    imageUrl: 'https://i.imgur.com/DxnClQt.jpg',
    title: 'Crazy',
    artist: 'Lil Baby',
    album: 'Crazy',
    duration: '3:12',
    yearPublished: '2023',
    valuation: 85,
    originality: 8,
  },
  {
    imageUrl: 'https://i.imgur.com/DxnClQt.jpg',
    title: 'Crazy',
    artist: 'Lil Baby',
    album: 'Crazy',
    duration: '3:12',
    yearPublished: '2023',
    valuation: 85,
    originality: 8,
  },

  /////

  // {
  //   title: 'Bat Out of Hell',
  //   duration: '2:59',
  //   artist: 'The Pharcyde',
  //   valuation: 78,
  //   originality: 7,
  // },
  // {
  //   title: 'Legend',
  //   duration: '3:31',
  //   artist: 'The Pharcyde',
  //   valuation: 82,
  //   originality: 8,
  // },
  // {
  //   title: 'Born in the U.S.A.',
  //   duration: '0:52',
  //   artist: 'The Pharcyde',
  //   valuation: 88,
  //   originality: 9,
  // },
  // {
  //   title: 'Greatest Hits',
  //   duration: '5:35',
  //   artist: 'The Pharcyde',
  //   valuation: 77,
  //   originality: 6,
  // },
  // {
  //   title: '21',
  //   duration: '4:56',
  //   artist: 'The Pharcyde',
  //   valuation: 83,
  //   originality: 7,
  // },
  // {
  //   title: 'Purple Rain [Soundtrack]',
  //   duration: '3:55',
  //   artist: 'The Pharcyde',
  //   valuation: 85,
  //   originality: 9,
  // },
  // {
  //   title: 'Slippery When Wet',
  //   duration: '5:05',
  //   artist: 'The Pharcyde',
  //   valuation: 75,
  //   originality: 7,
  // },
  // {
  //   title: 'Appetite For Destruction',
  //   duration: '0:42',
  //   artist: 'The Pharcyde',
  //   valuation: 80,
  //   originality: 8,
  // },
  // {
  //   title: 'The Joshua Tree',
  //   duration: '2:44',
  //   artist: 'The Pharcyde',
  //   valuation: 90,
  //   originality: 9,
  // },
  // {
  //   title: 'Metallica',
  //   duration: '5:35',
  //   artist: 'The Pharcyde',
  //   valuation: 92,
  //   originality: 9,
  // },
];
